pipeline {
    agent any

    tools {
        jfrog 'jfrog'
        maven 'Maven 3.8.3'
        jdk 'jdk8'
        //docker 'docker' // Assuming 'docker' is the tool name for Docker in your Jenkins configuration
    }
    environment {
        "docker pull hggosa.jfrog.io/docker/cloudsheger/jenkins-docker-latest:latest"
    }

    stages {
        stage('Build') {
            steps {
                script {
                    dir('java-app') {
                        // Corrected the command to use the 'maven' tool
                        sh 'mvn clean install'
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir('java-app') {
                        sh 'mvn test'
                    }
                }
            }
        }
        stage('Build Docker image') {
            steps {
                script {
                    dir('java-app') {
                        // Use the 'docker' tool to build the Docker image
                        sh "docker build -t cloudsheger/jenkins-docker-latest ."
                    }
                }
            }
        }
        stage('Scan and push image') {
            steps {
                script {
                    dir('java-app') {
                        // Assuming 'jf' is a shorthand for running JFrog CLI commands
                        // Corrected the syntax for scanning Docker images
                        //sh "jfrog docker scan $DOCKER_IMAGE_NAME"
                        sh "docker push cloudsheger/jenkins-docker-latest"
                    }
                }
            }
        }
        stage('Publish build info') {
            steps {
                script {
                    // Assuming 'jf' is a shorthand for running JFrog CLI commands
                    sh 'jfrog rt build-publish'
                }
            }
        }
    }
}
