pipeline {
    agent any
     stages {
        stage('Build') {
            steps {
                sh 'cd java-app && mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'cd java-app && mvn test'
            }
        }
    }
} 

// you will add other stages one by one - try this on jenkin
        
        

